# See https://github.com/netlify/netlify-cms/blob/master/example/config.yml
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# display_url: https://netlify-cms-react-starter.netlify.com # This url will display in the top-right of the CMS
media_folder: "public/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections: # A list of collections the CMS should be able to edit
  - name: calendarweeks
    label: Kalenderwochen
    label_singular: Kalenderwoche
    description: Alle Einträge werden später für die Ausgabe nach KW sortiert
    extension: json
    editor:
      preview: false
    folder: content/calendarweeks
    create: true
    fields:
      - label: Kalenderwoche (YYYY-CW)
        name: title
        widget: string
      - label: Sichtbar
        name: visible
        widget: boolean
        default: false
        required: false
      - label: Bild
        name: image
        widget: image
      - label: Name
        name: image_name
        widget: string
      - label: Beschreibung
        name: image_description
        widget: text
      - label: Fotos
        name: photos
        widget: list
        fields:
          - label: Bild
            name: image
            widget: image
          - label: Wochentag
            name: day
            widget: select
            options:
              - Mo
              - Di
              - Mi
              - Do
              - Fr
              - Sa
              - So
          - label: Beschreibung
            name: description
            widget: text

  - name: "settings"
    label: "Settings"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - file: "content/settings/global.yml"
        label: "Global Settings"
        name: "global-settings"
        fields:
          - {label: Site Title, name: siteTitle, widget: string}
          - {label: Site Url, name: siteUrl, widget: string, required: false}
          - {label: Site Description, name: siteDescription, widget: text, required: false}
          - label: Social Media Card
            name: socialMediaCard
            widget: object
            fields:
              - {label: Image, name: image, widget: image, required: false}
              - {label: Twitter Site Account, name: twitterSiteAccount, widget: string, required: false}
              - {label: Twitter Creator Account, name: twitterCreatorAccount, widget: string, required: false}
          - {label: Header Meta / Scripts, name: headerScripts, widget: text, required: false}
          - {label: Enable Service Worker Pre-Cache, name: enableServiceWorker, widget: boolean, required: false}
